### ISSUE TITLE
Building a project without a lockfile.jdn

### ISSUE THREAD

**Issue by giodamelio** [turnerdev/janet-nix#1]
I am new to both Janet and Nix and am trying to use this flake build [Judge](https://github.com/ianthehenry/judge). The problem is that Judge doesn't have a `lockfile.jdn`. Checking out `mkJanet` it seems like there needs to be a lockfile to allow it to fetch the sources. Is it possible to generate a lockfile if one doesn't exist?

The only solution I have working right now is to fork judge and add one.

My package:

```nix
judge = janet-nix.packages.x86_64-linux.mkJanet {
  name = "judge";
  src = pkgs.fetchFromGitHub {
    owner = "ianthehenry";
    repo = "judge";
    rev = "v2.4.0";
    sha256 = "sha256-ef2ol4k36tRCDyOdvBXu38t2U3baMRBM4b+eWOikW7w=";
  };
  entry = "./src/judge";
};
```

**Comment by giodamelio** [comment]
Even with the fork I can't get it to work, since Judge uses `declare-binscript`.

**Comment by turnerdev** [comment]
Hey @giodamelio apologies for the late response, only just saw this. I actually ran into this same issue when trying to build with Judge recently, I'll take a look see what options are available

**Comment by giodamelio** [comment]
No worries at all. I am pretty new to Nix and brand new to Janet, so thanks for providing this project to hack on.

**Comment by giodamelio** [comment]
Thanks for the quick update! I will give it a shot this weekend.

**Comment by turnerdev** [comment]
I've added a new attribute `extraDeps` to pass dependencies directly to `mkJanet`, so it's possible to generate the sources in advance:
```base
~/repos/judge $ jpm make-lockfile && nix run github:turnerdev/janet-nix
...
[
  { url = "https://github.com/ianthehenry/cmd"; rev = "7551225818a8a5f6665a918f1862db0c7704a1f4"; submodules = true; }
]
```

Unfortunately I still run into issues trying to build a working derivation for Judge. I got close with this:

```nix
{
  judge = janet-nix.packages.${system}.mkJanet {
    name = "judge";
    src = builtins.fetchGit {
      url = "https://github.com/ianthehenry/judge";
      rev = "c2a7eadf6cbf9ffad6f880c2ddbdbc03009a655f";
    };
    extraDeps = [{
      url = "https://github.com/ianthehenry/cmd";
      rev = "7551225818a8a5f6665a918f1862db0c7704a1f4";
    }];
    main = ''
      (import cmd)
      (import judge/runner)
      (defn main [& args]
        (put root-env :syspath (string (os/getenv "JANET_TREE") "/lib"))
        (setdyn *executable* "")
        (setdyn *args* (drop 1 (dyn *args*)))
        (cmd/main runner/main)
        (main))
    '';
  };
}
```

But it seems `declare-binscript` output expects to be interpreted as a script rather than run as a standalone binary. Passing a modified version of `src/judge` to the new `main` attribute gets it to build and run, but it still has issues.

After giving it more thought, it probably makes sense to just install Judge into the local environment via `jpm install`, since the tests `(use judge)` anyway. For an example see https://github.com/turnerdev/janet-nix/blob/main/templates/full/flake.nix#L71-L76

Thanks again for the feedback!
